### ISSUE TITLE
希望你能翻译一下Json5的项目

### ISSUE THREAD

**Issue by huiyifyj** [chinanf-boy/chinese-translate-list#1]
如题。
`Json5`是对现有的json语言的优化，他在`ECMAScript 5.1`被提出来。
项目地址：https://github.com/json5/json5.
虽然有人提交中文[`PR`](https://github.com/json5/json5/pull/167)，但是翻译根本不完全，而且也很久没有补充commit改善。

**Comment by chinanf-boy** [comment]
## 可以是可以

**但**， 我有点拿不准, 

### Readme

主项目的Readme，好像就给了点关于`json5`大的信息，翻译可以

- [ ] Readme.md翻译

### 官方规范-https://json5.github.io/json5-spec/

这份文档，拿不准，

> 而且好丑的网页

https://github.com/json5/json5-spec.git

- [ ] 不知道要不要？？？

**Comment by huiyifyj** [comment]
也没办法，不仅JSON5只是扩展语言，文档肯定不会过多。只需要对readme文档翻译就OK吧。

**Comment by chinanf-boy** [comment]
@huiyifyj 好了, **校对校对**

https://github.com/chinanf-boy/json5-zh

### 那个[PR](https://github.com/json5/json5/pull/167),还挂在那里, 如果你`PR`上json5/json5的话

把目录往下[的md内容复制复制](https://github.com/chinanf-boy/json5-zh#json5---%E4%BA%BA%E7%B1%BB%E7%9A%84-json)，再自己Fork，自己提交下吧 😊

**Comment by huiyifyj** [comment]
谦虚了吧。。。

**Comment by chinanf-boy** [comment]
@huiyifyj 如果没有问题，我希望，由提问者，自行关闭Issue, 谢谢
